signUpLogo = 'SIGN UP'
fieldEmail = '//android.widget.EditText[@resource-id="com.lavendrapp.lavendr:id/et_email"]'
fieldName = '//android.widget.EditText[@resource-id="com.lavendrapp.lavendr:id/et_first_name"]'
fieldPassword = '//android.widget.EditText[@resource-id="com.lavendrapp.lavendr:id/et_password"]'
fieldBirthDay = '//android.widget.EditText[@resource-id="com.lavendrapp.lavendr:id/et_birthday"]'
btnRegister = 'Register'
nmbrFive = '//android.view.View[@text="5"]'
logInButton = 'Log In'
